<?php


?>
<div style="padding: 0 30px">
    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><a name="bookmark0"><strong><span style="font-size:12.0pt"><span style="background-color:aqua">Пользовательское соглашение об условиях использования</span></span></strong></a></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:aqua">мобильного приложения </span></span></strong><strong><span style="font-size:12.0pt"><span style="background-color:aqua"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">&laquo;</span></span></span></strong><strong><span style="font-size:12.0pt"><span style="background-color:aqua">Price</span></span></strong><strong> </strong><strong><span style="font-size:12.0pt"><span style="background-color:aqua">Click</span></span></strong><strong><span style="font-size:12.0pt"><span style="background-color:aqua"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">&raquo;</span></span></span></strong></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Настоящее пользовательское соглашение регулирует отношения между ТОО &laquo;VALTON&raquo; (далее Владелец приложения), и лицом, использующим мобильное приложение</span> <span style="font-size:12.0pt">&laquo;</span><span style="font-size:12.0pt">Price</span> <span style="font-size:12.0pt">Click</span><span style="font-size:12.0pt">&raquo; (далее Пользователь), а вместе именуемых Стороны.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Использование мобильного приложения &laquo;</span><span style="font-size:12.0pt">Price</span> <span style="font-size:12.0pt">Click</span><span style="font-size:12.0pt">&raquo; (далее мобильное приложение) возможно исключительно на условиях настоящего Соглашения.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Настоящее Соглашение, а также информация о товаре, представленная в Приложении, являются открытой и общедоступной информацией, а также публичной офертой Поставщика в соответствии со ст. 395 ГК РК от 27.12.1994 года, согласно условиям, которого Владелец Приложения предоставляет Пользователю безвозмездный доступ к Приложению на условиях настоящего Соглашения.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:aqua"><span style="color:#362f2d">ТЕРМИНЫ И ОПРЕДЕЛЕНИЯ</span></span></span></strong></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt">Пользовательское соглашение</span></strong><span style="font-size:12.0pt"> - настоящее соглашение, регламентирующее работу с мобильным приложением.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt">Мобильное приложение</span></strong><span style="font-size:12.0pt"> - программное обеспечение для портативных (мобильных) устройств, установленное или загружаемое Пользователем на такие устройства с помощью различных программных платформ, предназначенное для доступа к </span><span style="font-size:12.0pt">Price</span> <span style="font-size:12.0pt">Click</span><span style="font-size:12.0pt">.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt">Владелец приложения</span></strong><span style="font-size:12.0pt"> - Товарищество с ограниченной ответственностью &laquo;</span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">VALTON</span></span><span style="font-size:12.0pt">&raquo;, зарегистрированное в Республике Казахстан, БИН 171140000831.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt">Мобильное устройство </span></strong><span style="font-size:12.0pt">&shy;- смартфоны, планшетные компьютеры.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt">Пользователь</span></strong><span style="font-size:12.0pt"> - любое дееспособное лицо, достигшее 18 летнего возраста, прошедшее процедуру установки мобильного приложения на свое мобильное устройство и пользующее мобильным приложением на условиях настоящего соглашения.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt">Магазин</span></strong><span style="font-size:12.0pt"> - любое юридическое/физическое лицо, выступающее в качестве индивидуального предпринимател</span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">я,</span></span><span style="font-size:12.0pt"> имеющее свое фирменное название, в том числе логотип, осуществляющее продажу товара, а также оказывающее услуги Пользователю.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt">Товар</span></strong><span style="font-size:12.0pt"> - любой товар (продукция, услуг</span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">а</span></span><span style="font-size:12.0pt"> или иное предложение), размещенный в мобильном приложении.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt">Заказ</span></strong><span style="font-size:12.0pt"> - должным образом оформленная заявка Пользователя, на приобретение перечня Товаров.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt">Сведения</span></strong><span style="font-size:12.0pt"> - любые материалы и информация, предоставленные Магазином и указанные в мобильном приложении.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Прекращение Пользовательского соглашения по инициативе Пользователя - действия, направленные на удаление (уничтожение) мобильного приложения с мобильного устройства Пользователя. Прекращение Пользовательского соглашения по инициативе</span> <span style="font-size:12.0pt">Владельца Приложения </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">-</span></span><span style="font-size:12.0pt"> расторжение в одностороннем порядке настоящего Пользовательского соглашения по организационным или техническим причинам путем удаления мобильного приложения и возможности его использования. Прекращение Пользовательского отношения между</span> <span style="font-size:12.0pt">Владельцем Приложения </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">и </span></span><span style="font-size:12.0pt">Пользователем прекращаются с момента перехода по ссылке, содержащейся в мобильном приложении, на сайт третьего лица.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:aqua"><span style="color:#362f2d">1.&nbsp;ОБЩИЕ ПОЛОЖЕНИЯ</span></span></span></strong></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Пользователь подтверждает, что ознакомлен с условиями настоящего Пользовательского соглашения в полном объеме до начала</span> <span style="font-size:12.0pt">использования мобильного приложения. В случае несогласия с условиями Пользовательского оглашения в целом или какой-либо их части Пользователь не вправе использовать мобильное приложение.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Пользователь признает и безоговорочно</span> <span style="font-size:12.0pt">согласен, что установка мобильного приложения </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">и </span></span><span style="font-size:12.0pt">его дальнейшее использование является</span> <span style="font-size:12.0pt">подтверждением согласия со всеми условиями, указанными в настоящем Соглашении. Пользователь признает и безоговорочно согласен, что с момента установки мобильного приложения на мобильное устройство Пользователя, договор между Владельцем Приложения и Пользователем считается заключенным на условиях настоящего Пользовательского соглашения.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">&nbsp;Владелец Приложения признает Пользователем любое дееспособное лицо, достигшее 18-летнего возраста, прошедшее процедуру установки</span> <span style="font-size:12.0pt">мобильного приложения на </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">свое</span></span><span style="font-size:12.0pt"> мобильное устройство и пользующееся мобильным приложением только на условиях настоящего соглашения.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">&nbsp;Принимая условия настоящего Пользовательского соглашения, Пользователь подтверждает свое согласие на обработку его персональных данных (фамилия, имя, отчество, пол, телефон, адрес, электронный адрес, </span><span style="font-size:12.0pt"><span style="color:#262626">изображения, графику, фото</span></span><span style="font-size:12.0pt">), в том числе сбор, хранение, уточнение, удаление, использование, предоставление третьим лицам в целях исполнения настоящего Соглашения и реализации функционирования мобильного приложения, введенных при заказе товара, предусмотренного прейскурантом/меню, в том числе, но не ограничиваясь, для формирования и передачи ответа Пользователю, а также разрешения возможных претензий. Пользователь настоящим уведомлен, понимает и соглашается с тем, что Приложение может собирать обезличенные (без привязки к персональным данным Пользователя) статистические данные об использовании Приложения и в автоматическом режиме передавать их Владельцу Приложения. &nbsp;&nbsp;&nbsp; </span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Обработка персональных данных Пользователя осуществляется в целях надлежащего предоставления функциональных возможностей Приложения и услуг Магазинов</span><span style="font-size:12.0pt">, информирования о новостях, обновлениях </span><span style="font-size:12.0pt">сервисов, формирования и передачи ответов Пользователю, разрешения возможных претензий, улучшения безопасности использования Приложения, восстановления утраченного доступа</span><span style="font-size:12.0pt"> к</span><span style="font-size:12.0pt"> профилю в Приложении, анализа и мониторинга эффективности работы Приложения на основании собранных статистических данных.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Пользователь подтверждает свое согласие на передачу предоставленных им персональных данных третьим лицам (в том числе банкам, лицам в адрес которых банк по распоряжению Пользователя переводит денежные средства, при наличии таких функциональных возможностей) и их обработку третьими лицами в целях исполнения настоящего Соглашения и реализации функций Приложения, а также разрешения претензий, связанных с исполнением настоящего Соглашения. Настоящее согласие на обработку персональных данных Пользователя действительно с момента установки мобильного приложения Пользователем на его мобильное устройство и могут обрабатываться в течении срока деятельности Владельца Приложения. Хранение персональных данных осуществляется согласно действующему законодательству Республики Казахстан. </span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Пользователь несет полную ответственность за достоверность представляемых Владельцу Приложения персональных данных и наступившие в связи с этим последствия перед третьими лицами. В случае предоставления недостоверной информации Владелец Приложения вправе приостановить либо отказать Пользователю в регистрации или использовании функционала Приложения. </span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Владелец Приложения не несет ответственности за возникновение негативных последствий для Пользователя в результате предоставления им недостоверных сведений. Настоящее Соглашение может быть изменено и/или дополнено Владельцем Приложения в одностороннем порядке. При этом продолжение использования мобильного приложения после внесения изменений и/или дополнений в настоящее Соглашение означает согласие Пользователя с такими изменениями и/ или дополнениями. В связи с этим Пользователь обязуется регулярно отслеживать изменения в соответствующем разделе в Приложении и в Соглашении. В случае несогласия с условиями такого измененного Соглашения Пользователь обязан отказаться от дальнейшего использования мобильного приложения путем удаления (уничтожения) данного мобильного приложения с мобильного устройства пользователя. </span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Обращения, предложения и претензии физических и юридических лиц к Владельцу Приложения, связанные с содержанием и функционированием мобильного приложения, нарушениями прав и интересов третьих лиц, требований законодательства Республики Казахстан, а также для запросов </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">лиц,</span></span><span style="font-size:12.0pt"> уполномоченных законодательством Республики Казахстан, могут быть направлены на адрес электронной почты </span><span style="font-size:12.0pt">info</span><span style="font-size:12.0pt">@</span><span style="font-size:12.0pt">priceclick</span><span style="font-size:12.0pt">.</span><span style="font-size:12.0pt">kz</span><span style="font-size:12.0pt">.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Настоящее Пользовательское соглашение составлено в соответствии с законодательством Республики Казахстан. Вопросы, не урегулированные Пользовательским соглашением, подлежат разрешению в соответствии с законодательством Республики Казахстан.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Соглашаясь с условиями настоящего Пользовательского соглашения, Пользователь подтверждает свои право- и полную дееспособность, а также достоверность данных, введенных им при заказе товара, предусмотренного прейскурантом/меню, в том числе, ФИО, телефон, адрес, электронный адрес и принимает на себя всю ответственность за их точность, полноту и достоверность.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Пользователь принимает на себя все возможные риски, связанные с допущенными им ошибками и неточностями в предоставленных данных при заказе товара, предусмотренного прейскурантом/ меню, в том числе количеством заказанного товара.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Пользователь безоговорочно согласен, что</span> <span style="font-size:12.0pt">информация, указанная в мобильном приложении, в том числе о товаре, цене товара, может отличаться от фактической к моменту оформления заказа на соответствующий товар. Подтверждением цены заказанного товара, в том числе наличия товара, является сообщение магазина о цене такого товара, наличии заказанного товара.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">Пользователь признает и согласен, что товар, опубликованный на фотографии, может отличаться от действительного вида товара. Пользователь признает и безоговорочно согласен, что информация, указанная в мобильном приложении разделе &laquo;прейскурант/ меню&raquo;, может быть изменена магазином (в любое время без предварительного уведомления). Для получения актуальной информации о товарах, в том числе о наличии (количестве) товара, его цене, Пользователь обязан обращаться к продавцам/операторам магазина. Пользователь признает и безоговорочно согласен, что цены на товар магазина действительны на дату, указанную в мобильном приложении. Для получения актуальной информации о цене товара Пользователь обязан обращаться к продавцам/операторам магазина. Обращения, предложения и претензии Пользователя к&nbsp; продавцам/операторам магазина, связанные с нарушениями прав и интересов третьих лиц и Покупателей, требований законодательства Республики Казахстан, а также для запросов уполномоченных законодательством Республики Казахстан лиц должны быть направлены по адресу соответствующего Магазина, размещенного в Приложении.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:aqua"><span style="color:#362f2d">2. ФУНКЦИОНАЛЬНЫЕ ВОЗМОЖНОСТИ МОБИЛЬНОГО ПРИЛОЖЕНИЯ</span></span></span></strong></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">2.1. Мобильное приложение позволяет Пользователям изучить магазины, телефоны, стоимость товара в виде справочной информации, а также сделать заказ товара на условиях настоящего Пользовательского соглашения.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:aqua">3. ИНФОРМАЦИЯ О ТОВАРЕ</span></span></strong></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">3.1. Товар представлен в Приложении через фото-образцы, являющиеся собственностью.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">3.2. Сопровождающие товар фото-образцы являются только иллюстрациями и могут различаться с действительным товаром.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">3.3. Каждый фото-образец сопровождается текстовой информацией: ценой и описанием товара.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">3.4. Сопровождающие товар описания/характеристики не претендуют на исчерпывающую информативность и могут содержать опечатки.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">3.5. По просьбе Пользователя Магазин может предоставить (по телефону) прочую информацию, необходимую и достаточную, с точки зрения Пользователя, для принятия им решения о покупке товара.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">3.6. Все претензии, имеющиеся у Пользователя и иных третьих лиц по товарам и услугам Магазина, размещенным в Приложении, предъявляются исключительно администрации Магазина.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:aqua">4. ПОРЯДОК ПРИОБРЕТЕНИЯ ТОВАРА</span></span></strong></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">4.1. Заказы принимаются в соответствии с рабочим графиком Магазина.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">4.2. Пользователь вправе оформить заказ на любой товар, представленный в Приложении.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">4.3. Для того чтобы воспользоваться службой доставки Магазина, Пользователь соглашается предоставить точные и полные персональные данные, информацию о месте доставки товара и контактные телефоны.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">4.4. После оформления заказа Магазин, связывается с Пользователем по телефону для получения подтверждения заказа.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">4.5. Владелец Приложения не несет ответственности за перерывы в предоставлении услуг, связанные с техническими перебоями в работе оборудования и программного обеспечения. Вместе с тем Владелец Приложения обязуется принимать все разумные меры для предотвращения таких перебоев.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">4.6. В случае если Магазин не связался с Пользователем по</span> <span style="font-size:12.0pt">телефону с целью подтверждения заказа, Пользователю необходимо связаться с Магазином по телефонам, указанным в Приложении.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">4.7. Пользователь вправе отказаться от заказанного товара, заблаговременно поставив в известность об этом Магазин по телефону.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">4.8. В случае отсутствия заказанного Пользователем товара, либо недостаточного его количества, Магазин связывается с Покупателем для дальнейшей корректировки заказа.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:aqua">5. ДОСТАВКА И ПРИЕМКА-ПЕРЕДАЧА ТОВАРА</span></span></strong></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">5.1. Доставка товара, заказанного в Приложении, осуществляется в соответствии с рабочим графиком Магазина.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">5.2. Со стоимостью доставки Пользователь может ознакомиться на странице оформления заказа.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">5.3. Заказанный товар доставляется до дверей квартиры, офиса или до указанного адреса Пользователем (если это технически возможно).</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">5.4. При фактическом отсутствии возможности подхода к адресу доставки заказа, по независящим от сторон причинам, Магазин вправе изменить место доставки заказа предварительно договорившись с Пользователем, либо отказаться от доставки заказа в одностороннем порядке.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">5.5. Магазин обязан передать Пользователю заказанный Товар надлежащим образом, упакованный и маркированный, транспортировка и хранение которого осуществлены надлежащим образом и к которому прилагается чек на товары (если таковой требуется по законодательству). Все остальные документы предоставляются Магазином по предварительной заявке Пользователя.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">5.6. Пользователь несет ответственность за то, чтобы во время доставки заказа по указанному адресу он находился лично, либо его представитель (лицо, уполномоченное принять и оплатить доставленный заказ).</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">5.7. При принятии заказа от Магазина, Пользователь обязан осмотреть доставленный заказ и проверить его на соответствие, срок годности и качество, ассортимент и комплектность, целостность упаковки и внешний вид, а также проверить отсутствие механических и иных видимых повреждений. В случае отсутствия претензий, Пользователь оплачивает заказанный товар и доставку, если они не оплачены.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">5.8. При наличии законных оснований для возврата денежных средств Пользователю, возврат средств осуществляется через наличный расчет.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">5.9. Согласно условиям настоящего Соглашения Пользователь соглашается с тем, что право собственности на заказанный товар переходит к Пользователю с момента оплаты.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:aqua">6. ОПЛАТА ТОВАРА</span></span></strong></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">6.1. Способы оплаты товара указаны в Приложении. Порядок и условия оплаты заказанного товара оговариваются Пользователем непосредственно с Магазином.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:aqua">7. ПРАВА И ОБЯЗАННОСТИ ПОЛЬЗОВАТЕЛЯ</span></span></strong></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">7.1. Пользователь обязуется надлежащим образом соблюдать условия настоящего Пользовательского соглашения.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">7.2. Пользователю предоставляется право </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">использования мобильного приложения </span></span><span style="font-size:12.0pt">исключительно с целью личного некоммерческого использования. При этом Пользователь может </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">использовать мобильное приложение </span></span><span style="font-size:12.0pt">исключительно в соответствии с настоящим Соглашением.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">7.3. Пользователь обязуется не использовать мобильное приложение в нарушение прав и законных интересов правообладателей, третьих лиц, настоящего Пользовательского соглашения и законодательства Республики Казахстан.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">7.4. Пользователь обязуется принимать </span></span><span style="font-size:12.0pt">надлежащие меры для обеспечения сохранности его мобильного устройства и несет личную ответственность за доступ к его мобильному устройству третьих лиц.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">7.5. Пользователь несет полную ответственность за использование мобильного приложения и его </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">сервисов любыми способами, прямо не </span></span><span style="font-size:12.0pt">разрешенными в настоящем Пользовательском соглашении.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">7.6. Пользователь имеет право расторгнуть настоящее Пользовательское соглашение в </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">одностороннем порядке путем удаления (уничтожения) мобильного приложения с </span></span><span style="font-size:12.0pt">мобильного устройства Пользователя.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:aqua">8. ПРАВА И ОБЯЗАННОСТИ ВЛАДЕЛЬЦА ПРИЛОЖЕНИЯ</span></span></strong></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">8.1. Владелец приложения вправе передавать права и обязанности по настоящему Пользовательскому соглашению третьим лицам на основании заключенного между Владельцем приложения и третьим лицом договора в письменной форме, в целях исполнения настоящего Пользовательского соглашения, без </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">уведомления и дополнительного согласия </span></span><span style="font-size:12.0pt">Пользователя.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">8.2. Пользователь, соглашаясь</span></span><span style="font-size:12.0pt"> с данным Пользовательским соглашением</span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">, дает свое информированное и добровольное согласие на участие в </span></span><span style="font-size:12.0pt">стимулирующих, рекламных, маркетинговых и иных мероприятиях, направленных на продвижение услуг Владельца Приложения, партнеров Владельца Приложения и иных третьих лиц.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">8.3. Владелец приложения оставляет за собой право в любой момент расторгнуть настоящее Пользовательское соглашение по организационным или техническим </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">причинам в </span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">одностороннем порядке путем </span></span><span style="font-size:12.0pt">удаления мобильного приложения или блокировки возможности его использования.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">8.4. В целях улучшения функций мобильного приложения, Владелец оставляет за собой право проводить технические перерывы без уведомления Пользователя в виде приостановления работы мобильного приложения.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">8.5. Владелец Приложения не несет ответственности за негативные последствия и убытки, возникшие в результате событий и обстоятельств, находящихся вне сферы ее компетенции, а также за действия (бездействия) третьих лиц, в том числе за действия или бездействия Магазина.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">8.6. Владелец Приложения вправе заблокировать доступ Пользователя к Приложению в случае обнаружения нарушений Пользователем обязанностей, указанных в настоящем Соглашении.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">8.7. В целях улучшения и повышения стабильности работы Приложения Владелец Приложения вправе собирать, хранить и обрабатывать статистическую информацию об использовании Пользователем Приложения.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">8.8 Владелец&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Приложения вправе показывать рекламные сообщения, осуществлять рассылку на электронную почту Пользователя.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">8.9. Владелец Приложения вправе использовать, обрабатывать информацию о Пользователях в рекламных и маркетинговых целях.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><a name="bookmark2"><strong><span style="font-size:12.0pt"><span style="background-color:aqua">9. ГАРАНТИИ И ОТВЕТСТВЕННОСТЬ СТОРОН</span></span></strong></a></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">9.1. Для исполнения настоящего Пользовательского соглашения могут привлекаться третьи лица. Пользователь </span></span><span style="font-size:12.0pt">подтверждает, </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">что</span></span><span style="font-size:12.0pt"> указанным третьим лицам </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">предоставляются такие же права, как и </span></span><span style="font-size:12.0pt">обладателю прав на мобильное приложение, в том </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">числе в отношении персональных</span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;"> данных </span></span><span style="font-size:12.0pt">Пользователя.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">9.2. Пользователь гарантирует, что не будет </span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">предпринимать каких-либо действий, </span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">направленных исключительно на причинение ущерба </span></span><span style="font-size:12.0pt">Владельцу Приложения</span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">, магазинам, информация о которых размещена в мобильном приложении, правообладателям или иным лицам.</span></span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">9.3. В случае нарушения правил использования мобильного приложения, указанных настоящим Пользовательским соглашением, а также в случае </span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">нарушения пункта 9.2 настоящего </span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">Пользовательского соглашения, Пользователь </span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">обязуется возместить </span></span><span style="font-size:12.0pt">Владельцу Приложения</span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;"> ущерб, </span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">причиненный такими действиями, в соответствии с действующим законодательством РК.</span></span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">9.4. Если Пользователем не доказано обратное, </span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">любые действия, осуществленные с </span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">использованием его мобильного устройства, </span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">считаются</span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;"> совершенными соответствующим Пользователем. В случае несанкционированного </span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">доступа к его мобильному устройству </span></span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">Пользователь обязан незамедлительно сообщить об этом </span></span><span style="font-size:12.0pt">Владельцу Приложения</span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;"> путем направления письма на электронный адрес </span></span><span style="font-size:12.0pt">info</span><span style="font-size:12.0pt">@</span><span style="font-size:12.0pt">priceclick</span><span style="font-size:12.0pt">.</span><span style="font-size:12.0pt">kz</span><span style="font-size:12.0pt">.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">9</span></span><span style="font-size:12.0pt">.5. Владелец Приложения не гарантирует, что мобильное приложение и его отдельные элементы не содержат ошибок и будут функционировать в соответствии с ожиданиями Пользователя. Наличие ошибок или недостатков в мобильном приложении, которое в том числе ведет к невозможности функционирования мобильного приложения на мобильном устройстве Пользователя, не является основанием для обмена, возврата или ремонта такого мобильного устройства. Также Владелец Приложения не предоставляет гарантий относительно действительности (актуальности) информации, предоставляемой через мобильное приложение. Любая размещенная в мобильном приложении информация является результатом предоставления магазинами информации для ее размещения в мобильном приложении.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">9.6. Мобильное приложение может содержать ссылки на другие сайты, являющиеся результатом интеллектуальной деятельности третьих лиц и охраняемые в соответствии с законодательством Республики Казахстан, и размещенный на них контент или может предоставлять доступ к ним в сети Интернет (сайты третьих лиц). Указанные сайты и размещенный на них контент не проверяются Владельцем Приложения на</span><span style="font-size:12.0pt"> соответствие требованиям </span><span style="font-size:12.0pt">законодательства Республики Казахстан.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">9.7. Владелец Приложения не несет ответственность за любую информацию или контент, размещенные на сайтах третьих лиц, к которым Пользователь </span><span style="font-size:12.0pt">получает доступ, посредством мобильного </span><span style="font-size:12.0pt">приложения, включая, в том числе, любые мнения или утверждения, выраженные на сайтах третьих лиц.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">9.8. Пользователь признает и безоговорочно </span><span style="font-size:12.0pt">подтверждает, что с момента перехода Пользователя по ссылке,</span><span style="font-size:12.0pt"> содержащейся в </span><span style="font-size:12.0pt">Мобильном приложении, на сайт третьего лица, </span><span style="font-size:12.0pt">взаимоотношения </span><span style="font-size:12.0pt">Владельца Приложения</span> <span style="font-size:12.0pt">и Пользователя прекращаются, настоящее Пользовательское соглашение в дальнейшем не распространяется на Пользователя, и Владелец не несет ответственность за использование Пользователем контента, правомерность такого использования и качество контента, размещенного на сайтах третьих лиц.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">9.9. Владелец приложения не является Продавцом товара и не несет ответственности за качество товара, размещенного в электронном варианте в мобильном приложении.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">9.10. Владелец Приложения не несет ответственности за любые виды убытков, произошедшие вследствие использования Пользователем мобильного приложения или отдельных его частей/функций.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:aqua">10. ИСКЛЮЧИТЕЛЬНОЕ ПРАВО</span></span></strong></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">10.1. Исключительные права на мобильное приложение в целом и включаемые в его состав или используемые совместно с ним программы для ЭВМ, базы данных, картографические, справочно - информационные и прочие текстовые материалы, изображения и иные объекты авторских и/или смежных прав, а равно объекты патентных прав, товарные знаки, коммерческие обозначения и фирменные наименования, а также иные составляющие мобильного приложения (независимо от того, входят ли они в их состав или являются дополнительными компонентами и возможно ли их извлечение из </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">состава </span></span><span style="font-size:12.0pt">мобильного приложения и использование самостоятельно) в отдельности, защищены </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">и </span></span><span style="font-size:12.0pt">являются объектами исключительных прав Владельца Приложения и других правообладателей.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">10.2. Нарушение </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">целостности</span></span><span style="font-size:12.0pt"> мобильного приложения, нарушение систем защиты мобильного приложения, а также иные действия, нарушающие исключительные права Правообладателя на мобильное приложение, не допускается и влечет гражданско-правовую, административную либо уголовную ответственность в соответствии с законодательством Республики Казахстан, в том числе обязанность исполнить решение суда по требованию Правообладателя о признании права, о пресечении действий, нарушающих право или создающих угрозу его нарушения, о возмещении </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">убытков, о публикации решения суда о допущенном нарушении с указанием </span></span><span style="font-size:12.0pt">действительного Правообладателя, о возмещении убытков либо выплате компенсации.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">10.3. Исключительные права на любые результаты </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">переработки (модификации) мобильного приложения возникают и принадлежат </span></span><span style="font-size:12.0pt">Правообладателю.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><strong><span style="font-size:12.0pt"><span style="background-color:aqua">11. ЗАКЛЮЧИТЕЛЬНЫЕ ПОЛОЖЕНИЯ</span></span></strong></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">11.1. В случае возникновения любых споров или </span><span style="font-size:12.0pt"><span style="font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;">разногласий, связанных с исполнением настоящего</span></span><span style="font-size:12.0pt"> Пользовательского соглашения, Пользователь и Владелец Приложения приложат все усилия для их разрешения путем проведения переговоров между ними. В случае если споры не будут разрешены путем переговоров, споры подлежат разрешению в соответствующем суде по месту юридического нахождения ТОО &laquo;</span><span style="font-size:12.0pt">VALTON</span><span style="font-size:12.0pt">&raquo;.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">11.2 Настоящее Пользовательское соглашение вступает в силу для Пользователя с момента установления мобильного приложения на мобильное устройство Пользователя и действует до прекращения настоящего Пользовательского соглашения.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt">11.3. Если какое-либо из положений настоящего Пользовательского соглашения будет признано недействительным, это не оказывает влияния на действительность или применимость остальных положений настоящего соглашения.</span></span></span></p>

    <p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>

</div>